export type City = {
  name: string
  slug: string
  conjugation: string
}

export async function getCities(locale?: string): Promise<City[]> {
  const polishCities = [
    {"name": "Warszawa", "slug": "systemy-ppoz-warszawa", "conjugation": "w Warszawie"},
    {"name": "Kraków", "slug": "systemy-ppoz-krakow", "conjugation": "w Krakowie"},
    {"name": "Łódź", "slug": "systemy-ppoz-lodz", "conjugation": "w Łodzi"},
    {"name": "Wrocław", "slug": "systemy-ppoz-wroclaw", "conjugation": "we Wrocławiu"},
    {"name": "Poznań", "slug": "systemy-ppoz-poznan", "conjugation": "w Poznaniu"},
    {"name": "Gdańsk", "slug": "systemy-ppoz-gdansk", "conjugation": "w Gdańsku"},
    {"name": "Szczecin", "slug": "systemy-ppoz-szczecin", "conjugation": "w Szczecinie"},
    {"name": "Bydgoszcz", "slug": "systemy-ppoz-bydgoszcz", "conjugation": "w Bydgoszczy"},
    {"name": "Lublin", "slug": "systemy-ppoz-lublin", "conjugation": "w Lublinie"},
    {"name": "Białystok", "slug": "systemy-ppoz-bialystok", "conjugation": "w Białymstoku"},
    {"name": "Katowice", "slug": "systemy-ppoz-katowice", "conjugation": "w Katowicach"},
    {"name": "Gdynia", "slug": "systemy-ppoz-gdynia", "conjugation": "w Gdyni"},
    {"name": "Toruń", "slug": "systemy-ppoz-torun", "conjugation": "w Toruniu"},
    {"name": "Radom", "slug": "systemy-ppoz-radom", "conjugation": "w Radomiu"},
    {"name": "Częstochowa", "slug": "systemy-ppoz-czestochowa", "conjugation": "w Częstochowie"},
    {"name": "Rzeszów", "slug": "systemy-ppoz-rzeszow", "conjugation": "w Rzeszowie"},
    {"name": "Kielce", "slug": "systemy-ppoz-kielce", "conjugation": "w Kielcach"},
    {"name": "Gliwice", "slug": "systemy-ppoz-gliwice", "conjugation": "w Gliwicach"},
    {"name": "Olsztyn", "slug": "systemy-ppoz-olsztyn", "conjugation": "w Olsztynie"},
    {"name": "Opole", "slug": "systemy-ppoz-opole", "conjugation": "w Opolu"},
    {"name": "Elbląg", "slug": "systemy-ppoz-elblag", "conjugation": "w Elblągu"},
    {"name": "Płock", "slug": "systemy-ppoz-plock", "conjugation": "w Płocku"},
    {"name": "Gorzów Wielkopolski", "slug": "systemy-ppoz-gorzow-wielkopolski", "conjugation": "w Gorzowie Wielkopolskim"},
    {"name": "Zielona Góra", "slug": "systemy-ppoz-zielona-gora", "conjugation": "w Zielonej Górze"},
    {"name": "Kalisz", "slug": "systemy-ppoz-kalisz", "conjugation": "w Kaliszu"},
    {"name": "Legnica", "slug": "systemy-ppoz-legnica", "conjugation": "w Legnicy"},
    {"name": "Koszalin", "slug": "systemy-ppoz-koszalin", "conjugation": "w Koszalinie"},
    {"name": "Grudziądz", "slug": "systemy-ppoz-grudziadz", "conjugation": "w Grudziądzu"},
    {"name": "Jaworzno", "slug": "systemy-ppoz-jaworzno", "conjugation": "w Jaworznie"},
    {"name": "Sopot", "slug": "systemy-ppoz-sopot", "conjugation": "w Sopocie"},
    {"name": "Nowy Sącz", "slug": "systemy-ppoz-nowy-sacz", "conjugation": "w Nowym Sączu"},
    {"name": "Jastrzębie-Zdrój", "slug": "systemy-ppoz-jastrzebie-zdroj", "conjugation": "w Jastrzębiu-Zdroju"},
    {"name": "Siedlce", "slug": "systemy-ppoz-siedlce", "conjugation": "w Siedlcach"},
    {"name": "Słupsk", "slug": "systemy-ppoz-slupsk", "conjugation": "w Słupsku"},
    {"name": "Piła", "slug": "systemy-ppoz-pila", "conjugation": "w Pile"},
    {"name": "Ostrów Wielkopolski", "slug": "systemy-ppoz-ostrow-wielkopolski", "conjugation": "w Ostrowie Wielkopolskim"},
    {"name": "Ruda Śląska", "slug": "systemy-ppoz-ruda-slaska", "conjugation": "w Rudzie Śląskiej"},
    {"name": "Wałbrzych", "slug": "systemy-ppoz-walbrzych", "conjugation": "w Wałbrzychu"},
    {"name": "Tychy", "slug": "systemy-ppoz-tychy", "conjugation": "w Tychach"},
    {"name": "Bielsko-Biała", "slug": "systemy-ppoz-bielsko-biala", "conjugation": "w Bielsku-Białej"},
    {"name": "Pabianice", "slug": "systemy-ppoz-pabianice", "conjugation": "w Pabianicach"},
    {"name": "Zabrze", "slug": "systemy-ppoz-zabrze", "conjugation": "w Zabrzu"},
    {"name": "Bytom", "slug": "systemy-ppoz-bytom", "conjugation": "w Bytomiu"},
    {"name": "Racibórz", "slug": "systemy-ppoz-raciborz", "conjugation": "w Raciborzu"},
    {"name": "Chorzów", "slug": "systemy-ppoz-chorzow", "conjugation": "w Chorzowie"},
    {"name": "Lubin", "slug": "systemy-ppoz-lubin", "conjugation": "w Lubinie"},
    {"name": "Tarnów", "slug": "systemy-ppoz-tarnow", "conjugation": "w Tarnowie"},
    {"name": "Biała Podlaska", "slug": "systemy-ppoz-biala-podlaska", "conjugation": "w Białej Podlaskiej"},
    {"name": "Głogów", "slug": "systemy-ppoz-glogow", "conjugation": "w Głogowie"},
    {"name": "Konin", "slug": "systemy-ppoz-konin", "conjugation": "w Koninie"},
    {"name": "Leszno", "slug": "systemy-ppoz-leszno", "conjugation": "w Lesznie"},
    {"name": "Zamość", "slug": "systemy-ppoz-zamosc", "conjugation": "w Zamościu"},
    {"name": "Przemyśl", "slug": "systemy-ppoz-przemysl", "conjugation": "w Przemyślu"},
    {"name": "Kędzierzyn-Koźle", "slug": "systemy-ppoz-kedzierzyn-kozle", "conjugation": "w Kędzierzynie-Koźlu"},
    {"name": "Piotrków Trybunalski", "slug": "systemy-ppoz-piotrkow-trybunalski", "conjugation": "w Piotrkowie Trybunalskim"},
    {"name": "Grodzisk Wielkopolski", "slug": "systemy-ppoz-grodzisk-wielkopolski", "conjugation": "w Grodzisku Wielkopolskim"},
    {"name": "Gniezno", "slug": "systemy-ppoz-gniezno", "conjugation": "w Gnieźnie"},
    {"name": "Śrem", "slug": "systemy-ppoz-srem", "conjugation": "w Śremie"},
    {"name": "Wągrowiec", "slug": "systemy-ppoz-wagrowiec", "conjugation": "w Wągrowcu"},
    {"name": "Kościan", "slug": "systemy-ppoz-koscian", "conjugation": "w Kościanie"},
    {"name": "Rawicz", "slug": "systemy-ppoz-rawicz", "conjugation": "w Rawiczu"},
    {"name": "Jarocin", "slug": "systemy-ppoz-jarocin", "conjugation": "w Jarocinie"},
    {"name": "Września", "slug": "systemy-ppoz-wrzesnia", "conjugation": "we Wrześni"},
    {"name": "Środa Wielkopolska", "slug": "systemy-ppoz-sroda-wielkopolska", "conjugation": "w Środzie Wielkopolskiej"},
    {"name": "Nowy Tomyśl", "slug": "systemy-ppoz-nowy-tomysl", "conjugation": "w Nowym Tomyślu"},
    {"name": "Wolsztyn", "slug": "systemy-ppoz-wolsztyn", "conjugation": "w Wolsztynie"},
    {"name": "Krotoszyn", "slug": "systemy-ppoz-krotoszyn", "conjugation": "w Krotoszynie"},
    {"name": "Luboń", "slug": "systemy-ppoz-lubon", "conjugation": "w Luboniu"},
    {"name": "Swarzędz", "slug": "systemy-ppoz-swarzedz", "conjugation": "w Swarzędzu"},
    {"name": "Mosina", "slug": "systemy-ppoz-mosina", "conjugation": "w Mosinie"},
    {"name": "Murowana Goślina", "slug": "systemy-ppoz-murowana-goslina", "conjugation": "w Murowanej Goślinie"},
    {"name": "Dąbrowa Górnicza", "slug": "systemy-ppoz-dabrowa-gornicza", "conjugation": "w Dąbrowie Górniczej"},
    {"name": "Sosnowiec", "slug": "systemy-ppoz-sosnowiec", "conjugation": "w Sosnowcu"},
    {"name": "Mysłowice", "slug": "systemy-ppoz-myslowice", "conjugation": "w Mysłowicach"},
    {"name": "Siemianowice Śląskie", "slug": "systemy-ppoz-siemianowice-slaskie", "conjugation": "w Siemianowicach Śląskich"},
    {"name": "Rybnik", "slug": "systemy-ppoz-rybnik", "conjugation": "w Rybniku"},
    {"name": "Żory", "slug": "systemy-ppoz-zory", "conjugation": "w Żorach"},
    {"name": "Pszczyna", "slug": "systemy-ppoz-pszczyna", "conjugation": "w Pszczynie"},
    {"name": "Wodzisław Śląski", "slug": "systemy-ppoz-wodzislaw-slaski", "conjugation": "w Wodzisławiu Śląskim"},
    {"name": "Mikołów", "slug": "systemy-ppoz-mikolow", "conjugation": "w Mikołowie"},
    {"name": "Tarnowskie Góry", "slug": "systemy-ppoz-tarnowskie-gory", "conjugation": "w Tarnowskich Górach"},
    {"name": "Będzin", "slug": "systemy-ppoz-bedzin", "conjugation": "w Będzinie"},
    {"name": "Czeladź", "slug": "systemy-ppoz-czeladz", "conjugation": "w Czeladzi"},
    {"name": "Knurów", "slug": "systemy-ppoz-knurow", "conjugation": "w Knurowie"},
    {"name": "Orzesze", "slug": "systemy-ppoz-orzesze", "conjugation": "w Orzeszu"},
    {"name": "Łaziska Górne", "slug": "systemy-ppoz-laziska-gorne", "conjugation": "w Łaziskach Górnych"},
    {"name": "Piekary Śląskie", "slug": "systemy-ppoz-piekary-slaskie", "conjugation": "w Piekarach Śląskich"},
    {"name": "Świętochłowice", "slug": "systemy-ppoz-swietochlowice", "conjugation": "w Świętochłowicach"},
    {"name": "Zawiercie", "slug": "systemy-ppoz-zawiercie", "conjugation": "w Zawierciu"},
    {"name": "Dębica", "slug": "systemy-ppoz-debica", "conjugation": "w Dębicy"},
    {"name": "Stalowa Wola", "slug": "systemy-ppoz-stalowa-wola", "conjugation": "w Stalowej Woli"},
    {"name": "Mielec", "slug": "systemy-ppoz-mielec", "conjugation": "w Mielcu"},
    {"name": "Tomaszów Mazowiecki", "slug": "systemy-ppoz-tomaszow-mazowiecki", "conjugation": "w Tomaszowie Mazowieckim"},
    {"name": "Bełchatów", "slug": "systemy-ppoz-belchatow", "conjugation": "w Bełchatowie"},
    {"name": "Zduńska Wola", "slug": "systemy-ppoz-zdunska-wola", "conjugation": "w Zduńskiej Woli"},
    {"name": "Kutno", "slug": "systemy-ppoz-kutno", "conjugation": "w Kutnie"},
    {"name": "Skierniewice", "slug": "systemy-ppoz-skierniewice", "conjugation": "w Skierniewicach"},
    {"name": "Żyrardów", "slug": "systemy-ppoz-zyrardow", "conjugation": "w Żyrardowie"},
    {"name": "Pruszków", "slug": "systemy-ppoz-pruszkow", "conjugation": "w Pruszkowie"},
    {"name": "Legionowo", "slug": "systemy-ppoz-legionowo", "conjugation": "w Legionowie"},
    {"name": "Otwock", "slug": "systemy-ppoz-otwock", "conjugation": "w Otwocku"},
    {"name": "Piaseczno", "slug": "systemy-ppoz-piaseczno", "conjugation": "w Piasecznie"},
    {"name": "Wołomin", "slug": "systemy-ppoz-wolomin", "conjugation": "w Wołominie"},
    {"name": "Marki", "slug": "systemy-ppoz-marki", "conjugation": "w Markach"},
    {"name": "Ząbki", "slug": "systemy-ppoz-zabki", "conjugation": "w Ząbkach"},
    {"name": "Kobyłka", "slug": "systemy-ppoz-kobylka", "conjugation": "w Kobyłce"},
    {"name": "Józefów", "slug": "systemy-ppoz-jozefow", "conjugation": "w Józefowie"},
    {"name": "Sulejówek", "slug": "systemy-ppoz-sulejowek", "conjugation": "w Sulejówku"},
    {"name": "Zielonka", "slug": "systemy-ppoz-zielonka", "conjugation": "w Zielonce"},
    {"name": "Kórnik", "slug": "systemy-ppoz-kornik", "conjugation": "w Kórniku"},
    {"name": "Kostrzyn", "slug": "systemy-ppoz-kostrzyn", "conjugation": "w Kostrzynie"},
    {"name": "Puszczykowo", "slug": "systemy-ppoz-puszczykowo", "conjugation": "w Puszczykowie"},
    {"name": "Stęszew", "slug": "systemy-ppoz-steszew", "conjugation": "w Stęszewie"},
    {"name": "Buk", "slug": "systemy-ppoz-buk", "conjugation": "w Buku"},
    {"name": "Opalenica", "slug": "systemy-ppoz-opalenica", "conjugation": "w Opalenicy"},
    {"name": "Lwówek", "slug": "systemy-ppoz-lwowek", "conjugation": "w Lwówku"},
    {"name": "Rakoniewice", "slug": "systemy-ppoz-rakoniewice", "conjugation": "w Rakoniewicach"},
    {"name": "Wielichowo", "slug": "systemy-ppoz-wielichowo", "conjugation": "w Wielichowie"},
    {"name": "Grodzisk Mazowiecki", "slug": "systemy-ppoz-grodzisk-mazowiecki", "conjugation": "w Grodzisku Mazowieckim"},
    {"name": "Żywiec", "slug": "systemy-ppoz-zywiec", "conjugation": "w Żywcu"},
    {"name": "Andrychów", "slug": "systemy-ppoz-andrychow", "conjugation": "w Andrychowie"},
    {"name": "Wadowice", "slug": "systemy-ppoz-wadowice", "conjugation": "w Wadowicach"},
    {"name": "Oświęcim", "slug": "systemy-ppoz-oswiecim", "conjugation": "w Oświęcimiu"},
    {"name": "Chrzanów", "slug": "systemy-ppoz-chrzanow", "conjugation": "w Chrzanowie"},
    {"name": "Trzebinia", "slug": "systemy-ppoz-trzebinia", "conjugation": "w Trzebini"},
    {"name": "Olkusz", "slug": "systemy-ppoz-olkusz", "conjugation": "w Olkuszu"},
    {"name": "Świnoujście", "slug": "systemy-ppoz-swinoujscie", "conjugation": "w Świnoujściu"},
    {"name": "Stargard", "slug": "systemy-ppoz-stargard", "conjugation": "w Stargardzie"},
    {"name": "Kołobrzeg", "slug": "systemy-ppoz-kolobrzeg", "conjugation": "w Kołobrzegu"},
    {"name": "Szczecinek", "slug": "systemy-ppoz-szczecinek", "conjugation": "w Szczecinku"},
    {"name": "Police", "slug": "systemy-ppoz-police", "conjugation": "w Policach"},
    {"name": "Świecie", "slug": "systemy-ppoz-swiecie", "conjugation": "w Świeciu"},
    {"name": "Inowrocław", "slug": "systemy-ppoz-inowroclaw", "conjugation": "w Inowrocławiu"},
    {"name": "Włocławek", "slug": "systemy-ppoz-wloclawek", "conjugation": "we Włocławku"},
    {"name": "Brodnica", "slug": "systemy-ppoz-brodnica", "conjugation": "w Brodnicy"},
    {"name": "Chełmno", "slug": "systemy-ppoz-chelmno", "conjugation": "w Chełmnie"},
    {"name": "Nakło nad Notecią", "slug": "systemy-ppoz-naklo-nad-notecia", "conjugation": "w Nakle nad Notecią"},
    {"name": "Rypin", "slug": "systemy-ppoz-rypin", "conjugation": "w Rypinie"},
    {"name": "Żnin", "slug": "systemy-ppoz-znin", "conjugation": "w Żninie"},
    {"name": "Szamotuły", "slug": "systemy-ppoz-szamotuly", "conjugation": "w Szamotułach"},
    {"name": "Oborniki", "slug": "systemy-ppoz-oborniki", "conjugation": "w Obornikach"},
    {"name": "Trzcianka", "slug": "systemy-ppoz-trzcianka", "conjugation": "w Trzciance"},
    {"name": "Czarnków", "slug": "systemy-ppoz-czarnkow", "conjugation": "w Czarnkowie"},
    {"name": "Chodzież", "slug": "systemy-ppoz-chodziez", "conjugation": "w Chodzieży"},
    {"name": "Złotów", "slug": "systemy-ppoz-zlotow", "conjugation": "w Złotowie"},
    {"name": "Jastrowie", "slug": "systemy-ppoz-jastrowie", "conjugation": "w Jastrowiu"},
    {"name": "Wronki", "slug": "systemy-ppoz-wronki", "conjugation": "we Wronkach"},
    {"name": "Rogoźno", "slug": "systemy-ppoz-rogozno", "conjugation": "w Rogoźnie"},
    {"name": "Międzychód", "slug": "systemy-ppoz-miedzychod", "conjugation": "w Międzychodzie"},
    {"name": "Sieraków", "slug": "systemy-ppoz-sierakow", "conjugation": "w Sierakowie"},
    {"name": "Krajenka", "slug": "systemy-ppoz-krajenka", "conjugation": "w Krajence"},
    {"name": "Zbąszyń", "slug": "systemy-ppoz-zbaszyn", "conjugation": "w Zbąszyniu"},
    {"name": "Nowy Targ", "slug": "systemy-ppoz-nowy-targ", "conjugation": "w Nowym Targu"},
    {"name": "Zakopane", "slug": "systemy-ppoz-zakopane", "conjugation": "w Zakopanem"},
    {"name": "Myślenice", "slug": "systemy-ppoz-myslenice", "conjugation": "w Myślenicach"},
    {"name": "Bochnia", "slug": "systemy-ppoz-bochnia", "conjugation": "w Bochni"},
    {"name": "Wieliczka", "slug": "systemy-ppoz-wieliczka", "conjugation": "w Wieliczce"},
    {"name": "Brzesko", "slug": "systemy-ppoz-brzesko", "conjugation": "w Brzesku"},
    {"name": "Dąbrowa Tarnowska", "slug": "systemy-ppoz-dabrowa-tarnowska", "conjugation": "w Dąbrowie Tarnowskiej"},
    {"name": "Mielec", "slug": "systemy-ppoz-mielec", "conjugation": "w Mielcu"},
    {"name": "Kolbuszowa", "slug": "systemy-ppoz-kolbuszowa", "conjugation": "w Kolbuszowej"},
    {"name": "Jarosław", "slug": "systemy-ppoz-jaroslav", "conjugation": "w Jarosławiu"},
    {"name": "Przeworsk", "slug": "systemy-ppoz-przeworsk", "conjugation": "w Przeworsku"},
    {"name": "Lubaczów", "slug": "systemy-ppoz-lubaczow", "conjugation": "w Lubaczowie"},
    {"name": "Sanok", "slug": "systemy-ppoz-sanok", "conjugation": "w Sanoku"},
    {"name": "Ustrzyki Dolne", "slug": "systemy-ppoz-ustrzyki-dolne", "conjugation": "w Ustrzykach Dolnych"},
    {"name": "Krosno", "slug": "systemy-ppoz-krosno", "conjugation": "w Krośnie"},
    {"name": "Jasło", "slug": "systemy-ppoz-jaslo", "conjugation": "w Jaśle"},
    {"name": "Gorlice", "slug": "systemy-ppoz-gorlice", "conjugation": "w Gorlicach"},
    {"name": "Nowa Sól", "slug": "systemy-ppoz-nowa-sol", "conjugation": "w Nowej Soli"},
    {"name": "Żagań", "slug": "systemy-ppoz-zagan", "conjugation": "w Żaganiu"},
    {"name": "Żary", "slug": "systemy-ppoz-zary", "conjugation": "w Żarach"},
    {"name": "Lubań", "slug": "systemy-ppoz-luban", "conjugation": "w Lubaniu"},
    {"name": "Bolesławiec", "slug": "systemy-ppoz-boleslawiec", "conjugation": "w Bolesławcu"},
    {"name": "Jelenia Góra", "slug": "systemy-ppoz-jelenia-gora", "conjugation": "w Jeleniej Górze"},
    {"name": "Kłodzko", "slug": "systemy-ppoz-klodzko", "conjugation": "w Kłodzku"},
    {"name": "Świdnica", "slug": "systemy-ppoz-swidnica", "conjugation": "w Świdnicy"},
    {"name": "Dzierżoniów", "slug": "systemy-ppoz-dzierzoniow", "conjugation": "w Dzierżoniowie"},
    {"name": "Oława", "slug": "systemy-ppoz-olawa", "conjugation": "w Oławie"},
    {"name": "Brzeg", "slug": "systemy-ppoz-brzeg", "conjugation": "w Brzegu"},
    {"name": "Nysa", "slug": "systemy-ppoz-nysa", "conjugation": "w Nysie"},
    {"name": "Strzelce Opolskie", "slug": "systemy-ppoz-strzelce-opolskie", "conjugation": "w Strzelcach Opolskich"},
    {"name": "Głubczyce", "slug": "systemy-ppoz-glubczyce", "conjugation": "w Głubczycach"},
    {"name": "Prudnik", "slug": "systemy-ppoz-prudnik", "conjugation": "w Prudniku"},
    {"name": "Namysłów", "slug": "systemy-ppoz-namyslow", "conjugation": "w Namysłowie"},
    {"name": "Kluczbork", "slug": "systemy-ppoz-kluczbork", "conjugation": "w Kluczborku"},
    {"name": "Olesno", "slug": "systemy-ppoz-olesno", "conjugation": "w Oleśnie"},
    {"name": "Brzeg Dolny", "slug": "systemy-ppoz-brzeg-dolny", "conjugation": "w Brzegu Dolnym"},
    {"name": "Wołów", "slug": "systemy-ppoz-wolow", "conjugation": "w Wołowie"},
    {"name": "Trzebnica", "slug": "systemy-ppoz-trzebnica", "conjugation": "w Trzebnicy"},
    {"name": "Milicz", "slug": "systemy-ppoz-milicz", "conjugation": "w Miliczu"},
    {"name": "Ostrzeszów", "slug": "systemy-ppoz-ostrzeszow", "conjugation": "w Ostrzeszowie"},
    {"name": "Syców", "slug": "systemy-ppoz-sycow", "conjugation": "w Sycowie"},
    {"name": "Turek", "slug": "systemy-ppoz-turek", "conjugation": "w Turku"},
    {"name": "Kłodawa", "slug": "systemy-ppoz-klodawa", "conjugation": "w Kłodawie"},
    {"name": "Dąbie", "slug": "systemy-ppoz-dabie", "conjugation": "w Dąbiu"},
    {"name": "Słupca", "slug": "systemy-ppoz-slupca", "conjugation": "w Słupcy"},
    {"name": "Golina", "slug": "systemy-ppoz-golina", "conjugation": "w Golinie"},
    {"name": "Kleczew", "slug": "systemy-ppoz-kleczew", "conjugation": "w Kleczewie"},
    {"name": "Sompolno", "slug": "systemy-ppoz-sompolno", "conjugation": "w Sompolnie"},
    {"name": "Rychwał", "slug": "systemy-ppoz-rychwal", "conjugation": "w Rychwale"},
    {"name": "Skulsk", "slug": "systemy-ppoz-skulsk", "conjugation": "w Skulsku"},
    {"name": "Grabów nad Prosną", "slug": "systemy-ppoz-grabow-nad-prosna", "conjugation": "w Grabowie nad Prosną"},
    {"name": "Kobylin", "slug": "systemy-ppoz-kobylin", "conjugation": "w Kobylinie"},
    {"name": "Zduny", "slug": "systemy-ppoz-zduny", "conjugation": "w Zdunach"},
    {"name": "Mikstat", "slug": "systemy-ppoz-mikstat", "conjugation": "w Mikstacie"},
    {"name": "Raszków", "slug": "systemy-ppoz-raszkow", "conjugation": "w Raszkowie"},
    {"name": "Odolanów", "slug": "systemy-ppoz-odolanow", "conjugation": "w Odolanowie"},
    {"name": "Przygodzice", "slug": "systemy-ppoz-przygodzice", "conjugation": "w Przygodzicach"},
    {"name": "Sośnie", "slug": "systemy-ppoz-sosnie", "conjugation": "w Sośniach"},
    {"name": "Barlinek", "slug": "systemy-ppoz-barlinek", "conjugation": "w Barlinku"},
    {"name": "Myślibórz", "slug": "systemy-ppoz-mysliborz", "conjugation": "w Myśliborzu"},
    {"name": "Choszczno", "slug": "systemy-ppoz-choszczno", "conjugation": "w Choszcznie"},
    {"name": "Drawsko Pomorskie", "slug": "systemy-ppoz-drawsko-pomorskie", "conjugation": "w Drawsku Pomorskim"},
    {"name": "Złocieniec", "slug": "systemy-ppoz-zlocieniec", "conjugation": "w Złocieńcu"},
    {"name": "Czaplinek", "slug": "systemy-ppoz-czaplinek", "conjugation": "w Czaplinku"},
    {"name": "Białogard", "slug": "systemy-ppoz-bialogard", "conjugation": "w Białogardzie"},
    {"name": "Karlino", "slug": "systemy-ppoz-karlino", "conjugation": "w Karlinie"},
    {"name": "Tychowo", "slug": "systemy-ppoz-tychowo", "conjugation": "w Tychowie"},
    {"name": "Połczyn-Zdrój", "slug": "systemy-ppoz-polczyn-zdroj", "conjugation": "w Połczynie-Zdroju"},
    {"name": "Świdwin", "slug": "systemy-ppoz-swidwin", "conjugation": "w Świdwinie"},
    {"name": "Łobez", "slug": "systemy-ppoz-lobez", "conjugation": "w Łobzie"},
    {"name": "Resko", "slug": "systemy-ppoz-resko", "conjugation": "w Resku"},
    {"name": "Gryfice", "slug": "systemy-ppoz-gryfice", "conjugation": "w Gryficach"},
    {"name": "Płoty", "slug": "systemy-ppoz-ploty", "conjugation": "w Płotach"},
    {"name": "Trzebiatów", "slug": "systemy-ppoz-trzebiatow", "conjugation": "w Trzebiatowie"},
    {"name": "Gryfino", "slug": "systemy-ppoz-gryfino", "conjugation": "w Gryfinie"},
    {"name": "Nowogard", "slug": "systemy-ppoz-nowogard", "conjugation": "w Nowogardzie"},
    {"name": "Goleniów", "slug": "systemy-ppoz-goleniow", "conjugation": "w Goleniowie"},
    {"name": "Maszewo", "slug": "systemy-ppoz-maszewo", "conjugation": "w Maszewie"},
    {"name": "Stepnica", "slug": "systemy-ppoz-stepnica", "conjugation": "w Stepnicy"},
    {"name": "Międzyzdroje", "slug": "systemy-ppoz-miedzyzdroje", "conjugation": "w Międzyzdrojach"},
    {"name": "Dziwnów", "slug": "systemy-ppoz-dziwnow", "conjugation": "w Dziwnowie"},
    {"name": "Kamień Pomorski", "slug": "systemy-ppoz-kamien-pomorski", "conjugation": "w Kamieniu Pomorskim"},
    {"name": "Wolin", "slug": "systemy-ppoz-wolin", "conjugation": "w Wolinie"},
    {"name": "Międzywodzie", "slug": "systemy-ppoz-miedzywodzie", "conjugation": "w Międzywodziu"},
    {"name": "Rewal", "slug": "systemy-ppoz-rewal", "conjugation": "w Rewalu"},
    {"name": "Pobierowo", "slug": "systemy-ppoz-pobierowo", "conjugation": "w Pobierowie"},
    {"name": "Mrzeżyno", "slug": "systemy-ppoz-mrzezyno", "conjugation": "w Mrzeżynie"},
    {"name": "Dźwirzyno", "slug": "systemy-ppoz-dzwirzyno", "conjugation": "w Dźwirzynie"},
    {"name": "Grzybowo", "slug": "systemy-ppoz-grzybowo", "conjugation": "w Grzybowie"},
    {"name": "Ustronie Morskie", "slug": "systemy-ppoz-ustronie-morskie", "conjugation": "w Ustroniu Morskim"},
    {"name": "Sarbinowo", "slug": "systemy-ppoz-sarbinowo", "conjugation": "w Sarbinowie"},
    {"name": "Mielno", "slug": "systemy-ppoz-mielno", "conjugation": "w Mielnie"},
    {"name": "Unieście", "slug": "systemy-ppoz-uniescie", "conjugation": "w Unieściu"},
    {"name": "Łazy", "slug": "systemy-ppoz-lazy", "conjugation": "w Łazach"},
    {"name": "Dąbki", "slug": "systemy-ppoz-dabki", "conjugation": "w Dąbkach"},
    {"name": "Darłowo", "slug": "systemy-ppoz-darlowo", "conjugation": "w Darłowie"},
    {"name": "Ustka", "slug": "systemy-ppoz-ustka", "conjugation": "w Ustce"},
    {"name": "Jastarnia", "slug": "systemy-ppoz-jastarnia", "conjugation": "w Jastarni"},
    {"name": "Władysławowo", "slug": "systemy-ppoz-wladyslawowo", "conjugation": "we Władysławowie"},
    {"name": "Hel", "slug": "systemy-ppoz-hel", "conjugation": "w Helu"},
    {"name": "Puck", "slug": "systemy-ppoz-puck", "conjugation": "w Pucku"},
    {"name": "Reda", "slug": "systemy-ppoz-reda", "conjugation": "w Redzie"},
    {"name": "Rumia", "slug": "systemy-ppoz-rumia", "conjugation": "w Rumii"},
    {"name": "Wejherowo", "slug": "systemy-ppoz-wejherowo", "conjugation": "w Wejherowie"},
    {"name": "Kartuzy", "slug": "systemy-ppoz-kartuzy", "conjugation": "w Kartuzach"},
    {"name": "Żukowo", "slug": "systemy-ppoz-zukowo", "conjugation": "w Żukowie"},
    {"name": "Pruszcz Gdański", "slug": "systemy-ppoz-pruszcz-gdanski", "conjugation": "w Pruszczu Gdańskim"},
    {"name": "Tczew", "slug": "systemy-ppoz-tczew", "conjugation": "w Tczewie"},
    {"name": "Starogard Gdański", "slug": "systemy-ppoz-starogard-gdanski", "conjugation": "w Starogardzie Gdańskim"},
    {"name": "Skarszewy", "slug": "systemy-ppoz-skarszewy", "conjugation": "w Skarszewach"},
    {"name": "Pelplin", "slug": "systemy-ppoz-pelplin", "conjugation": "w Pelplinie"},
    {"name": "Gniew", "slug": "systemy-ppoz-gniew", "conjugation": "w Gniewie"},
    {"name": "Kwidzyn", "slug": "systemy-ppoz-kwidzyn", "conjugation": "w Kwidzynie"},
    {"name": "Sztum", "slug": "systemy-ppoz-sztum", "conjugation": "w Sztumie"},
    {"name": "Malbork", "slug": "systemy-ppoz-malbork", "conjugation": "w Malborku"},
    {"name": "Nowy Dwór Gdański", "slug": "systemy-ppoz-nowy-dwor-gdanski", "conjugation": "w Nowym Dworze Gdańskim"},
    {"name": "Krynica Morska", "slug": "systemy-ppoz-krynica-morska", "conjugation": "w Krynicy Morskiej"},
    {"name": "Stegna", "slug": "systemy-ppoz-stegna", "conjugation": "w Stegnie"},
    {"name": "Jantar", "slug": "systemy-ppoz-jantar", "conjugation": "w Jantarze"},
    {"name": "Sztutowo", "slug": "systemy-ppoz-sztutowo", "conjugation": "w Sztutowie"},
    {"name": "Kąty Rybackie", "slug": "systemy-ppoz-katy-rybackie", "conjugation": "w Kątach Rybackich"},
    {"name": "Mikoszewo", "slug": "systemy-ppoz-mikoszewo", "conjugation": "w Mikoszewie"},
    {"name": "Sobieszewo", "slug": "systemy-ppoz-sobieszewo", "conjugation": "w Sobieszewie"},
    {"name": "Chałupy", "slug": "systemy-ppoz-chalupy", "conjugation": "w Chałupach"},
    {"name": "Kuźnica", "slug": "systemy-ppoz-kuznica", "conjugation": "w Kuźnicy"},
    {"name": "Jurata", "slug": "systemy-ppoz-jurata", "conjugation": "w Juracie"}
  ];

  // For Polish locale, return cities with conjugation
  if (locale === "pl") {
    return polishCities;
  }

  // For other locales (English, etc.), return cities without conjugation
  // Just use the city name since the dictionary already includes "in"
  return polishCities.map(city => ({
    ...city,
    conjugation: city.name
  }));
}
